---
sidebar: sidebar 
permalink: concept_api_operation.html 
keywords: rest api, deploy rest api, rest, operation, basic operation 
summary: REST建立一套通用的技術和最佳實務做法、但每個API的詳細資料可能會因設計選項而異。在使用API之前、您應該先瞭解ONTAP Select 到「更新部署API」的詳細資料和操作特性。 
---
= 基本營運特性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
REST建立一套通用的技術和最佳實務做法、但每個API的詳細資料可能會因設計選項而異。在使用API之前、您應該先瞭解ONTAP Select 到「更新部署API」的詳細資料和操作特性。



== Hypervisor主機與ONTAP Select 非節點

Hypervisor主機_是裝載ONTAP Select 一個整套虛擬機器的核心硬體平台。當在Hypervisor主機上部署及啟用某部支援的虛擬機器時、該虛擬機器被視為_這個節點_。ONTAP Select ONTAP Select在部署REST API的第3版中、主機和節點物件是分開且獨立的。這可建立一對多關係、讓一或多ONTAP Select 個支援節點可在同一個Hypervisor主機上執行。



== 物件識別碼

每個資源執行個體或物件在建立時都會指派一個唯一的識別碼。這些識別碼在ONTAP Select 特定的例子中是全域唯一的。發出建立新物件執行個體的 API 呼叫後、會將相關的 ID 值傳回給中的呼叫者 `location` HTTP回應的標頭。您可以擷取識別碼、並在參照資源執行個體時用於後續通話。


NOTE: 物件識別碼的內容和內部結構可隨時變更。當您參照相關的物件時、只能視需要在適用的API呼叫上使用識別碼。



== 要求識別碼

每個成功的API要求都會指派一個唯一的識別碼。識別碼會傳回至 `request-id` 相關 HTTP 回應的標頭。您可以使用要求識別碼、統稱為單一特定API要求回應交易的活動。例如、您可以根據要求ID擷取交易的所有事件訊息。



== 同步和非同步呼叫

伺服器執行從用戶端接收的HTTP要求的主要方法有兩種：

* 同步
伺服器會立即執行要求、並以 200 、 201 或 204 的狀態碼回應。
* 非同步
伺服器接受要求、並以狀態代碼 202 回應。這表示伺服器已接受用戶端要求、並開始執行背景工作以完成要求。最終成功或失敗無法立即取得、必須透過額外的API呼叫來判斷。




== 確認已完成長時間執行的工作

一般而言、任何可能需要較長時間才能完成的作業、都會使用非同步處理
伺服器的背景工作。使用部署 REST API 時、每個背景工作都會以錨定
工作物件、可追蹤工作並提供資訊、例如目前狀態。工作物件、
在建立背景工作之後、 HTTP 回應會傳回其唯一識別碼、

您可以直接查詢「工作」物件、以判斷相關聯的API呼叫是否成功。
如需其他資訊、請參閱_使用工作物件進行非同步處理_。

除了使用工作物件之外、還有其他方法可以判斷的成功或失敗
申請、包括：

* 事件訊息
您可以使用傳回原始回應的要求 ID 、擷取與特定 API 呼叫相關的所有事件訊息。事件訊息通常包含成功或失敗的指示、也可在偵錯錯誤條件時使用。
* 資源狀態
有幾個資源會維持一個狀態或狀態值、您可以查詢該值、以間接判斷要求的成功或失敗。




== 安全性

部署API使用下列安全技術：

* 傳輸層安全性
透過網路在部署伺服器和用戶端之間傳送的所有流量都會透過 TLS 加密。不支援在未加密的通道上使用HTTP傳輸協定。支援TLS 1.2版。
* HTTP 驗證
每項 API 交易都會使用基本驗證。每個要求都會新增一個HTTP標頭、其中包含基礎64字串中的使用者名稱和密碼。

